apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-registry
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/rskruhak/thanos-lab-gitops.git
    targetRevision: HEAD
    path: apps/image-registry
    directory:
      exclude: 'application.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-image-registry
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: imageregistry.operator.openshift.io
      kind: Config
      jsonPointers:
        - /spec
        - /status
